name = "museum-visitors-api"
compatibility_date = "2025-01-01"
main = "api.worker.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "VISITORS_DB"
database_name = "museum-visitors"
database_id = "b2de3fe3-fd66-467a-8473-82fbe3a15958"
