name = "museum-visitors-api"
compatibility_date = "2024-06-20"
main = "api.worker.ts"

[vars]
# You can define environment variables here

[[d1_databases]]
binding = "VISITORS_DB"
database_name = "museum-visitors"
database_id = "b2de3fe3-fd66-467a-8473-82fbe3a15958"
